# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c58cb3a5abcb267a1490a8430f9c513d77dd0cfb3db16e659336d785c111784d283a9c000ba2c55ca54670732b045b6669f395d6dc038cef5c367536bb5c3cf0

test:
  secret_key_base: d41dba3a185af75b5cd988130d4cc55a8122d027b0478bdd4120d87377738dfe82c58c7b403e38304e1881fa34e22fdda4bdd336589ba46cc666a16a1da7204b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
